DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS comments;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE admins (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	admin_name TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE transfers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	sender_id INTEGER NOT NULL,
	account_no DECIMAL(26) NOT NULL,
	amount DECIMAL(7,2) NOT NULL,
	title TEXT NOT NULL,
	accepted INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (sender_id) REFERENCES user (id)
);

CREATE TABLE comments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	comment TEXT NOT NULL
);

